# Generated by Django 5.1.6 on 2025-02-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_start_date', models.DateField()),
                ('trip_end_date', models.DateField()),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='locations.location')),
            ],
        ),
    ]
