# Generated by Django 5.1.6 on 2025-03-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_itinerary_user_remove_itinerary_locations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='user',
            new_name='owner',
        ),
    ]
