# Generated by Django 5.1.6 on 2025-03-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_initial'),
        ('itineraries', '0003_rename_user_itinerary_owner'),
    ]

    operations = [
    ]
