# Generated by Django 5.1.6 on 2025-03-02 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_merge_0002_initial_0003_rename_user_itinerary_owner'),
        ('locations', '0005_remove_location_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='trip_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='trip_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='locations',
        ),
        
        migrations.CreateModel(
            name='ItineraryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_visit_date', models.DateField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerary')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        
        migrations.AddField(
            model_name='itinerary',
            name='locations',
            field=models.ManyToManyField(
                related_name='itineraries',
                through='itineraries.ItineraryLocation',
                to='locations.location'
            ),
        ),
    ]
