# Generated by Django 5.1.6 on 2025-02-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='month_from',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'Febraury'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')]),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='month_to',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'Febraury'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')]),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='name',
            field=models.CharField(choices=[('Spring', 'Spring 🌸'), ('Summer', 'Summer ☀️'), ('Autumn', 'Autumn 🍂'), ('Winter', 'Winter ❄️')]),
        ),
    ]
