# Generated by Django 5.1.6 on 2025-02-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_alter_seasons_month_from_alter_seasons_month_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='month_from',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')]),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='month_to',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')]),
        ),
    ]
