# Generated by Django 5.1.6 on 2025-02-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_seasons_month_from_alter_seasons_month_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasons',
            old_name='month_from',
            new_name='end_month',
        ),
        migrations.RenameField(
            model_name='seasons',
            old_name='month_to',
            new_name='start_month',
        ),
    ]
