# Generated by Django 5.1.7 on 2025-03-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_tags', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_image', models.CharField(blank=True, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('search_tags', models.ManyToManyField(related_name='locations', to='search_tags.searchtags')),
                ('seasons', models.ManyToManyField(related_name='seasonal_locations', to='seasons.seasons')),
            ],
        ),
    ]
