# Generated by Django 5.1.6 on 2025-02-26 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0002_alter_seasons_month_from_alter_seasons_month_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_image', models.CharField(blank=True, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('visit_date', models.DateTimeField()),
                ('tags', models.IntegerField()),
                ('seasons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='seasons.seasons')),
            ],
        ),
    ]
