# Generated by Django 5.1.6 on 2025-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('search_tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='tags',
        ),
        migrations.AddField(
            model_name='location',
            name='search_tags',
            field=models.ManyToManyField(related_name='locations', to='search_tags.searchtags'),
        ),
    ]
