# Generated by Django 5.1.6 on 2025-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_tags_location_search_tags'),
        ('seasons', '0002_alter_seasons_month_from_alter_seasons_month_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='seasons',
        ),
        migrations.AddField(
            model_name='location',
            name='seasons',
            field=models.ManyToManyField(related_name='seasonal_locations', to='seasons.seasons'),
        ),
    ]
