# Generated by Django 5.1.6 on 2025-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_location_seasons_location_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
